---
title: "HW2"
author: "Bin Lin"
date: "2016-09-11"
output: html_document
---


2.6 Dice rolls.

(a) getting a sum of 1?   0
(b) getting a sum of 5?   1/9
(c) getting a sum of 12?  1/36


2.8 Poverty and language.

(a) Are living below the poverty line and speaking a foreign language at home disjoint? 
No


(b) Draw a Venn diagram summarizing the variables and their associated probabilities. 
```{r}
#install.packages("VennDiagram")

library(VennDiagram)
draw.pairwise.venn(area1 = 14.6, area2 = 20.7, cross.area = 4.2, category = c('% Below the Powerty Line', '% Foreign Languege Speaker'), cat.pos = c(3, -1))
```

(c) What percent of Americans live below the poverty line and only speak English at home? 

16.5%


(d) What percent of Americans live below the poverty line or speak a foreign language at home? 

31.1%


(e) What percent of Americans live above the poverty line and only speak English at home? 

68.9%


(f) Is the event that someone lives below the poverty line independent of the event that the person speaks a foreign language at home

P(A and B) = 4.2%
P(A) * P(B) = 16.5 * 10.4 = 1.716%
P(A and B) != P(A) * P(B)
So they are not independent



2.20 Assortative mating.
(a) What is the probability that a randomly chosen male respondent or his partner has blue eyes? 

(78+23+13+19+11)/204=70.59%


(b) What is the probability that a randomly chosen male respondent with blue eyes has a partner with blue eyes?
P(Blue|Blue) = P(Blue and Blue) / P(Blue) = 78/114 = 68.42%



(c) What is the probability that a randomly chosen male respondent with brown eyes has a partner with blue eyes? What about the probability of a randomly chosen male respondent with green eyes having a partner with blue eyes? 

P(Blue|Brown) = P(Blue and Brown) / P(Brown) = 19 / 54 = 35.19%
P(Blue|Green) = P(Blue and Green) / P(Green) = 11/36 = 30.56%


(d) Does it appear that the eye colors of male respondents and their partners are independent? Explain your reasoning.

P(Blue)= 114/204 = 55.88% != P(Blue|Blue) != P(Blue|Brown) != P(Blue|Green)
So that eye colors of male respondents and their partners are not independent. 


2.30 Books on a bookshelf.
(a) Find the probability of drawing a hardcover book ???rst then a paperback ???ction book second when drawing without replacement. 

28/95 * 67/(95-1) = 21.01%


(b) Determine the probability of drawing a ???ction book ???rst and then a hardcover book second, when drawing without replacement. 

72/95 * (13/72 * 27/94 + 59/72 * 28/94) = 22.43%


(c) Calculate the probability of the scenario in part (b), except this time complete the calculations under the scenario where the ???rst book is placed back on the bookcase before randomly drawing the second book. 

72/95 * 28/95 = 22.34%


(d) The ???nal answers to parts (b) and (c) are very similar. Explain why this is the case.

Because if it is without replacement, what is going to happen is the book we draw could be the hardcover fiction book. Therefore, when we draw a second book, the sample pool has changed. However, if it is with replacement, the sample pool will always be the same. 


2.38 Baggage fees.
(a) Build a probability model, compute the average revenue per passenger, and compute the corresponding standard deviation. 

E(X) = 54% * 0 + 34% * 25 + 12% * 60 =15.7
V(X)= 0.54 * (0 - 15.7) ^ 2 + 0.34 * (25 - 15.7)^2 + 0.12 * (60 - 15.7) ^ 2 = 398.01
S(X) = sqrt(V(X)) = 19.95


(b) About how much revenue should the airline expect for a ???ight of 120 passengers? With what standard deviation? Note any assumptions you make and if you think they are justi???ed.

E(120X) = 120 * E(X) = 120 * 15.7= 1884
V(120X) = 120^2 * V(X) = 120^2 * 398.01 = 5731344
S(120) = sqrt(V(120X)) = 2394



2.44 Income and gender.

(a) Describe the distribution of total personal income. 

It is a bell shape curve. 



(b) What is the probability that a randomly chosen US resident makes less than $50,000 per year? 

P(less than $50000) = 21.2% + 18.3% + 15.8% + 4.7% + 2.2% = 62.2%



(c) What is the probability that a randomly chosen US resident makes less than$50,000 per year and is female? Note any assumptions you make. 

96420486 * 0.622 * 0.41 = 24589152
My assumption is the gender and personal income are two independent random variables. 



(d) The same data source indicates that 71.8% of females make less than $50,000 per year. Use this value to determine whether or not the assumption you made in part (c) is valid.

P(less than $50000) = 62.2% 
P(Female) = 41%
P(Female | less than 50000) != P(Female)
Therefore, the personal income and gender are two dependent random variable. 


